### ISSUE TITLE
Nothing is rendered

### ISSUE THREAD

**Issue by hajimehoshi** [200sc/sprite-demo#2]
`go run core.go` resulted in:

```
[oak]-------- Adding demo
[oak]-------- No logs directory found. No logs will be written to file.
[config:143]  [{{assets/ audio/ images/ font/} { ERROR} {480 640} {none 12 72  white} 60 60 false English Oak Window}]

~~~~~~~~~~~~~~~
Oak Seed: 1500758209299222026

~~~~~~~~~~~~~~~
[load:92]  [open /Users/hajimehoshi/go/src/github.com/200sc/sprite-demo/assets/audio: no such file or directory]
[loading:28]  [open /Users/hajimehoshi/go/src/github.com/200sc/sprite-demo/assets/audio: no such file or directory]
```

**Comment by 200sc** [comment]
You have to press K to spawn sprites. Does that work? Or are you saying no window spawned?

**Comment by 200sc** [comment]
It's worth considering starting with some number of sprites like Ebiten's demo does (done by 29f78bd), and / or adding a remove sprites button, but the readme should probably say the spawn button. (done by b719115)

**Comment by 200sc** [comment]
I've tested it on windows and linux 64-bit with oak's master branch, and it seems to work. It's possible if the window didn't open at all that there's an uncommon crash we failed to detect, or maybe it's something to do with OS beyond the two I checked?

**Comment by hajimehoshi** [comment]
Thanks, pressing K worked.

**Comment by hajimehoshi** [comment]
> maybe it's something to do with OS beyond the two I checked?

I was using macOS and this worked.
